# Syntaxe : ${NOM_VARIABLE:-valeur_par_defaut}
project:
  name: credit_card_fraud_detection

training:
  backend: scikitlearn

model:
  name: random_forest_classifier

  params:
    max_depth: null
    n_estimators: 200

  persistence:
    type: joblib

tracking:
  backend: mlflow
  uri: "{{?MLFLOW_URI}}"
  type: sqlite
  store_name: mlflow.db

logs:
  file_size_max: 50MB
  level: "{{LOG_LEVEL}}"
  storage:
    backend: elasticsearch
    url: "{{LOG_STORAGE_URL}}"