project:
  name: credit_card_fraud_detection

model:
  name: random_forest_classifier

  params:
    max_depth: null
    n_estimators: 200

  persistence:
    type: joblib

mlflow:
  backend:
    type: sqlite
    name: mlflow.db